### ISSUE TITLE
nuxi init with npm is very slow

### ISSUE THREAD

**Issue by devhawk** [nuxt/cli#411] opened 2024-05-14 16:17 UTC
Creating a new nuxt app with `nuxi` using npm as package manager takes almost 6 minutes. Using pnpm takes 8 seconds, yarn 16 seconds, bun 4 seconds. I get that npm is slower than more modern package managers, but 20x slower seems longer than I would have expected

```shell
> npx nuxi@latest init arctic-demon

✔ Which package manager would you like to use?
npm
◐ Installing dependencies...                                                                                9:04:38 AM

> postinstall
> nuxt prepare

✔ Types generated in .nuxt                                                                                 9:10:29 AM
```

**Comment by shinGangan** [comment] 2024-05-20 09:32
Hi @devhawk , I tried it in my environment and couldn't observe it being that slow.

- `Node: v20.5.0`
- `npm: v9.8.0`

Is this problem still occurring?
If it is continuing, it would be a good idea to include environment information such as Node and npm versions.
You may be able to gather opinions from people in the same environment.

**Comment by devhawk** [comment] 2024-05-20 18:03
node: v20.13.1
npm: v10.8.0
os: Debian 12 (via Windows Subsystem for Linux)

**Comment by devhawk** [comment] 2024-05-20 18:06
I tried installing Node v20.5 + which came with NPM 9.8 and the issue went away. took 23 seconds to install dependencies instead of almost 6 minutes

**Comment by shinGangan** [comment] 2024-05-20 18:39
@devhawk 

Has this problem been resolved once?

This problem is most likely caused by the OS, Node, or npm rather than Nuxt CLI.
Therefore, if it is currently resolved, I think it is okay to close it.

If it happens again, please open it again.

**Comment by shinGangan** [comment] 2024-05-20 21:24
Sorry, @devhawk .

It would be helpful if you could close it when you have time 🙏

**Closed** 2024-05-21 17:38 UTC
